In [4]:
%run Functions.ipynb

In [6]:
%run Dataset.ipynb

Connection successful!
PostgreSQL 17.5 on x86_64-windows, compiled by msvc-19.43.34808, 64-bit

In [7]:
customers

,id,customer_id,name,dob,email_id,city,update_date
0,1,CUST_001,Rohan Mehta,1992-05-16,rohit.mehta92@gmail.com,Jaipur,2024-09-20
1,2,CUST_001,Rohan Mehta,1992-05-16,rohit.mehta5@rediffmail.com,Kota,2025-05-18
2,3,CUST_001,Rohan Mehta,1992-05-16,rohit.16@outlook.com,Bikaner,2020-11-14
3,4,CUST_002,Priya Sharma,1988-09-22,priya.sharma88@yahoo.com,Patna,2018-12-23
4,5,CUST_002,Priya Sharma,1988-09-22,Priya.sharma@gamil.com,Gaya,2025-04-29
5,6,CUST_003,Arjun Reddy,1995-03-10,arjun.reddy10@outlook.com,Mumbai,2025-05-15
6,7,CUST_004,Neha Kapoor,1990-12-05,neha.kapoor90@gmail.com,Nasik,2024-07-13
7,8,CUST_004,Neha Kapoor,1990-12-05,Neha05@outlook.com,Pune,2025-05-09
8,9,CUST_005,Amitabh Das,1985-07-18,amitabh.das85@gmail.com,Kolkata,2025-02-24
9,10,CUST_006,Ananya Patel,1993-04-12,ananya.patel93@gmail.com,Ahmedabad,2024-08-15
10,11,CUST_006,Ananya Patel,1993-04-12,ananya.p12@rediffmail.com,Surat,2025-03-22
11,12,CUST_007,Vikram Singh,1987-11-30,vikram.singh87@yahoo.com,Lucknow,2019-06-18
12,13,CUST_008,Meera Nair,1991-08-25,meera.nair91@gmail.com,Chennai,2025-01-10
13,14,CUST_008,Meera Nair,1991-08-25,meera.25@outlook.com,Coimbatore,2023-09-14
14,15,CUST_009,Rahul Verma,1989-02-14,rahul.verma89@gmail.com,Delhi,2024-11-05
15,16,CUST_010,Sneha Gupta,1994-07-08,sneha.gupta94@yahoo.com,Kanpur,2023-12-20
16,17,CUST_011,Karthik Iyer,1990-10-03,karthik.iyer90@gmail.com,Bangalore,2025-02-28
17,18,CUST_011,Karthik Iyer,1990-10-03,karthik.03@outlook.com,Mysore,2022-07-15
18,19,CUST_012,Pooja Joshi,1995-01-19,pooja.joshi95@gmail.com,Pune,2024-04-12
19,20,CUST_013,Aryan Malhotra,1986-06-22,aryan.malhotra86@yahoo.com,Chandigarh,2023-10-30
20,21,CUST_014,Divya Reddy,1992-09-17,divya.reddy92@gmail.com,Hyderabad,2025-03-05
21,22,CUST_014,Divya Reddy,1992-09-17,divya.17@rediffmail.com,Vishakapatnam,2021-08-22
22,23,CUST_015,Aditya Rao,1988-12-07,aditya.rao88@outlook.com,Mumbai,2024-07-19
23,24,CUST_016,Shreya Banerjee,1993-03-28,shreya.banerjee93@gmail.com,Kolkata,2025-01-25
24,25,CUST_017,Rajat Kapoor,1987-05-14,rajat.kapoor87@yahoo.com,Delhi,2023-11-11
25,26,CUST_018,Anjali Desai,1991-11-09,anjali.desai91@gmail.com,Ahmedabad,2024-09-03
26,27,CUST_019,Vivek Choudhary,1989-08-31,vivek.choudhary89@outlook.com,Jaipur,2025-04-17
27,28,CUST_020,Ishaani Sengupta,1994-02-26,ishaani.sengupta94@gmail.com,Kolkata,2023-07-08
28,29,CUST_021,Manish Agarwal,1985-04-15,manish.agarwal85@yahoo.com,Patna,2022-12-01
29,30,CUST_022,Tanvi Rana,1990-07-23,tanvi.rana90@gmail.com,Dehradun,2024-10-14
30,31,CUST_023,Siddharth Bose,1992-10-11,siddharth.bose92@outlook.com,Kolkata,2025-02-09
31,32,CUST_024,Nandini Menon,1988-01-30,nandini.menon88@gmail.com,Chennai,2023-05-22
32,33,CUST_025,Abhishek Saxena,1993-06-18,abhishek.saxena93@yahoo.com,Lucknow,2024-08-27
33,34,CUST_026,Preeti Chawla,1987-09-05,preeti.chawla87@gmail.com,Chandigarh,2025-03-12
34,35,CUST_027,Deepak Srinivasan,1991-12-24,deepak.srini91@outlook.com,Bangalore,2023-10-05
35,36,CUST_028,Anushka Trivedi,1994-03-17,anushka.trivedi94@gmail.com,Ahmedabad,2024-11-28
36,37,CUST_029,Rishi Malhotra,1986-08-08,rishi.malhotra86@yahoo.com,Delhi,2022-09-15
37,38,CUST_030,Maya Iyer,1990-05-21,maya.iyer90@gmail.com,Chennai,2025-01-07
38,39,CUST_031,Varun Khanna,1989-11-12,varun.khanna89@outlook.com,Mumbai,2024-06-19
39,40,CUST_032,Shivani Joshi,1992-04-03,shivani.joshi92@gmail.com,Pune,2023-12-14
40,41,CUST_033,Arun Kumar,1987-07-26,arun.kumar87@yahoo.com,Hyderabad,2025-04-02
41,42,CUST_034,Neeta Sharma,1993-10-15,neeta.sharma93@gmail.com,Jaipur,2024-07-21
42,43,CUST_035,Pranav Nair,1988-02-28,pranav.nair88@outlook.com,Bangalore,2023-11-30
43,44,CUST_036,Kavita Reddy,1991-09-09,kavita.reddy91@gmail.com,Hyderabad,2025-02-16
44,45,CUST_037,Harsh Gupta,1985-12-22,harsh.gupta85@yahoo.com,Kanpur,2022-10-08
45,46,CUST_038,Swati Mehra,1994-01-14,swati.mehra94@gmail.com,Delhi,2024-09-05
46,47,CUST_039,Rajeev Menon,1986-06-07,rajeev.menon86@outlook.com,Chennai,2023-08-12
47,48,CUST_040,Pallavi Rao,1990-08-19,pallavi.rao90@gmail.com,Bangalore,2025-03-24
48,49,CUST_041,Amit Sharma,1987-03-11,amit.sharma87@yahoo.com,Jaipur,2024-05-17
49,50,CUST_042,Divya Kapoor,1992-12-05,divya.kapoor92@gmail.com,Mumbai,2023-10-22
50,51,CUST_043,Rakesh Patel,1989-05-28,rakesh.patel89@outlook.com,Ahmedabad,2025-01-13
51,52,CUST_044,Anita Deshpande,1993-07-16,anita.deshpande93@gmail.com,Pune,2024-08-09
52,53,CUST_045,Vikram Bhat,1988-10-09,vikram.bhat88@yahoo.com,Bangalore,2023-12-27
53,54,CUST_046,Shalini Nair,1991-04-02,shalini.nair91@gmail.com,Chennai,2025-02-03
54,55,CUST_047,Rohit Verma,1986-11-25,rohit.verma86@outlook.com,Delhi,2024-07-14
55,56,CUST_048,Megha Srinivas,1990-02-18,megha.srinivas90@gmail.com,Hyderabad,2023-09-08
56,57,CUST_049,Alok Chaturvedi,1985-09-01,alok.chaturvedi85@yahoo.com,Lucknow,2022-11-19
57,58,CUST_050,Priyanka Banerjee,1994-06-12,priyanka.banerjee94@gmail.com,Kolkata,2025-04-05

In [8]:
accounts

     account_no account_type customer_id account_status activation_date
0   20001234567      Savings    CUST_001         Active      2021-01-15
1   20004578624      Current    CUST_001       Inactive      2019-05-22
2   20001498732        Demat    CUST_001         Active      2015-11-09
3   20002534697      Current    CUST_002         Active      2017-07-19
4   20009876543      Savings    CUST_002      Suspended      2023-02-15
5   20005678901      Savings    CUST_003         Active      2022-08-11
6   20008774153        Demat    CUST_004         Active      2024-04-03
7   20002345678      Current    CUST_004       Inactive      2022-06-18
8   20007890123      Savings    CUST_005         Active      2025-10-14
9   20001112233      Savings    CUST_006         Active      2020-03-12
10  20002223344      Current    CUST_006       Inactive      2018-07-25
11  20003334455      Savings    CUST_007         Active      2021-09-08
12  20004445566        Demat    CUST_007      Suspended      2019-11-30
13  20005556677      Current    CUST_008         Active      2022-02-14
14  20006667788      Savings    CUST_008         Active      2020-05-27
15  20007778899        Demat    CUST_009       Inactive      2017-08-10
16  20008889900      Savings    CUST_009         Active      2023-01-23
17  20009990011      Current    CUST_010         Active      2021-04-06
18  20001010122      Savings    CUST_010      Suspended      2019-06-19
19  20002121233        Demat    CUST_011         Active      2022-09-02
20  20003232344      Current    CUST_011       Inactive      2020-12-15
21  20004343455      Savings    CUST_012         Active      2023-03-28
22  20005454566        Demat    CUST_012         Active      2021-06-11
23  20006565677      Current    CUST_013      Suspended      2018-09-24
24  20007676788      Savings    CUST_013         Active      2024-01-07
25  20008787899        Demat    CUST_014       Inactive      2022-04-20
26  20009898900      Savings    CUST_014         Active      2020-07-03
27  20010909011      Current    CUST_015         Active      2023-10-16
28  20011010122        Demat    CUST_015         Active      2021-01-29
29  20012121233      Savings    CUST_016      Suspended      2018-04-12
30  20013232344      Current    CUST_016         Active      2024-07-25
31  20014343455        Demat    CUST_017       Inactive      2022-10-08
32  20015454566      Savings    CUST_017         Active      2020-01-21
33  20016565677      Current    CUST_018         Active      2023-04-04
34  20017676788        Demat    CUST_018         Active      2021-07-17
35  20018787899      Savings    CUST_019      Suspended      2018-10-30
36  20019898900      Current    CUST_019         Active      2024-02-12
37  20020909011        Demat    CUST_020       Inactive      2022-05-25
38  20021010122      Savings    CUST_020         Active      2020-08-08
39  20022121233      Current    CUST_021         Active      2023-11-21
40  20023232344        Demat    CUST_021         Active      2021-02-04
41  20024343455      Savings    CUST_022      Suspended      2018-05-17
42  20025454566      Current    CUST_022         Active      2024-08-30
43  20026565677        Demat    CUST_023       Inactive      2022-11-13
44  20027676788      Savings    CUST_023         Active      2020-02-26
45  20028787899      Current    CUST_024         Active      2023-06-09
46  20029898900        Demat    CUST_024         Active      2021-09-22
47  20030909011      Savings    CUST_025      Suspended      2018-12-05
48  20031010122      Current    CUST_025         Active      2024-03-18
49  20032121233        Demat    CUST_026       Inactive      2022-06-01
50  20033232344      Savings    CUST_026         Active      2020-09-14
51  20034343455      Current    CUST_027         Active      2023-12-27
52  20035454566        Demat    CUST_027         Active      2021-04-10
53  20036565677      Savings    CUST_028      Suspended      2018-07-23
54  20037676788      Current    CUST_028         Active      2024-10-06
55  20038787899        Demat    CUST_029       Inactive      2022-01-19
56  20039898900      Savings    CUST_029         Active      2020-04-02
57  20040909011      Current    CUST_030         Active      2023-07-15

In [9]:
transactions

    transaction_id   account_no customer_id    amount    transaction_time
0                1  20001234567    CUST_001  185000.0 2025-05-10 10:15:00
1                2  20004578624    CUST_001  -15000.0 2022-12-11 11:30:00
2                3  20001498732    CUST_001  -22000.0 2023-12-11 14:00:00
3                4  20002534697    CUST_002   15000.0 2025-01-05 15:45:00
4                5  20009876543    CUST_002   25000.0 2023-04-05 16:40:00
5                6  20005678901    CUST_003   65000.0 2024-02-18 11:00:00
6                7  20005678901    CUST_003  -16000.0 2023-09-22 13:25:00
7                8  20008774153    CUST_004   40000.0 2024-03-22 14:20:00
8                9  20002345678    CUST_004  -18000.0 2023-11-22 17:15:00
9               10  20007890123    CUST_005  100000.0 2024-04-10 09:00:00
10              11  20001112233    CUST_006  120000.0 2025-04-05 09:30:00
11              12  20002223344    CUST_006   -8000.0 2023-11-15 10:45:00
12              13  20003334455    CUST_007   75000.0 2024-12-20 11:20:00
13              14  20004445566    CUST_007  -12000.0 2022-08-10 14:30:00
14              15  20005556677    CUST_008   45000.0 2025-01-25 15:10:00
15              16  20006667788    CUST_008   18000.0 2023-06-18 16:25:00
16              17  20007778899    CUST_009   -9000.0 2021-09-22 10:15:00
17              18  20008889900    CUST_009   95000.0 2024-03-10 11:40:00
18              19  20009990011    CUST_010   60000.0 2024-11-05 13:20:00
19              20  20001010122    CUST_010  -15000.0 2022-04-15 14:45:00
20              21  20002121233    CUST_011  110000.0 2025-02-18 09:30:00
21              22  20003232344    CUST_011  -17000.0 2023-07-22 10:55:00
22              23  20004343455    CUST_012   85000.0 2024-10-12 12:30:00
23              24  20005454566    CUST_012   22000.0 2022-01-28 15:15:00
24              25  20006565677    CUST_013  -11000.0 2021-04-05 16:40:00
25              26  20007676788    CUST_013   78000.0 2024-07-30 09:25:00
26              27  20008787899    CUST_014  -14000.0 2023-02-14 11:50:00
27              28  20009898900    CUST_014   92000.0 2025-03-08 13:15:00
28              29  20010909011    CUST_015   55000.0 2024-09-22 14:40:00
29              30  20011010122    CUST_015   25000.0 2022-12-18 16:05:00
30              31  20012121233    CUST_016  -13000.0 2021-05-30 10:20:00
31              32  20013232344    CUST_016   87000.0 2024-08-15 11:45:00
32              33  20014343455    CUST_017  -16000.0 2023-01-20 13:10:00
33              34  20015454566    CUST_017   68000.0 2025-04-05 14:35:00
34              35  20016565677    CUST_018   48000.0 2024-10-28 16:00:00
35              36  20017676788    CUST_018  -10000.0 2022-03-12 09:25:00
36              37  20018787899    CUST_019  -12000.0 2021-08-17 10:50:00
37              38  20019898900    CUST_019  105000.0 2024-11-22 12:15:00
38              39  20020909011    CUST_020   -9000.0 2023-04-27 13:40:00
39              40  20021010122    CUST_020   72000.0 2025-01-10 15:05:00
40              41  20022121233    CUST_021   63000.0 2024-06-15 16:30:00
41              42  20023232344    CUST_021  -15000.0 2022-09-20 09:55:00
42              43  20024343455    CUST_022  -11000.0 2021-12-25 11:20:00
43              44  20025454566    CUST_022   89000.0 2024-05-30 12:45:00
44              45  20026565677    CUST_023  -14000.0 2023-08-05 14:10:00
45              46  20027676788    CUST_023   76000.0 2025-02-18 15:35:00
46              47  20028787899    CUST_024   52000.0 2024-07-23 17:00:00
47              48  20029898900    CUST_024   -8000.0 2022-10-28 09:25:00
48              49  20030909011    CUST_025  -10000.0 2021-01-03 10:50:00
49              50  20031010122    CUST_025   98000.0 2024-04-08 12:15:00
50              51  20032121233    CUST_026  -12000.0 2023-07-13 13:40:00
51              52  20033232344    CUST_026   84000.0 2025-03-18 15:05:00
52              53  20034343455    CUST_027   67000.0 2024-09-23 16:30:00
53              54  20035454566    CUST_027  -13000.0 2022-12-28 09:55:00
54              55  20036565677    CUST_028  -15000.0 2021-03-05 11:20:00
55              56  20037676788    CUST_028   91000.0 2024-06-10 12:45:00
56              57  20038787899    CUST_029  -11000.0 2023-09-15 14:10:00
57              58  20039898900    CUST_029   79000.0 2025-01-20 15:35:00
58              59  20040909011    CUST_030   58000.0 2024-08-25 17:00:00